### ISSUE TITLE
What about making constexpr mpreal's constructors?

### ISSUE THREAD

**Issue by abkein** [advanpix/mpreal#18]
Is it possible to make mpreal's constructor and other functions as `constexpr`?
And maybe tag functions as `noexcept`

**Comment by advanpix** [comment]
The `constexpr` is not suitable, as MPREAL constructor/functions must be used run-time (they cannot compute in compile-time). There is no real meaning in using `noexcept` too. 

We keep compatibility with C++03 and use only what is really necessary from C++11.
