### ISSUE TITLE
Maybe a bug: 8 to the power of 1/3 is 1 

### ISSUE THREAD

**Issue by abkein** [advanpix/mpreal#19]
Minimal working example:
```cpp
#include <iostream>
#include "mpreal.h"

int main(int argc, char const *argv[])
{
    mpfr::mpreal ux = 8;
    mpfr::mpreal vd = 1 / 3;
    std::cout << mpfr::pow(ux, vd) << std::endl;
    return 0;
}
```
Will print `1`
Or I don't understand something?

**Comment by advanpix** [comment]
Expression 1/3 = 0 by the rules of integer arithmetic in C++. Naturally 8^0 = 1, there is no bug.
Use `vd = mpfr::mpreal(1)/3` if you want to 8^(1/3).
