### ISSUE TITLE
How to fix argument issues using VS2019

### ISSUE THREAD

**Issue by bashanbro** [advanpix/mpreal#20]
I am using this tutorial (https://www.youtube.com/watch?v=SoBVqS2lN7E) to try to compile mpfr-4.2.0 and mpir-3.0.0 as dll files on VS2019, all is fine. But when using the example of mpreal.h, get the following errors:

_Error C2660 "mpfr::mpreal::mpfr_srcptr": the function does not accept 1 argument   D:\scitools\DevSoft\gmp\mpir\x64\Release\mpreal.h 590	
Error C2660 "mpfr_init2": the function does not accept 1 argument      D:\scitools\DevSoft\gmp\mpir\x64\Release\mpreal.h 590	
Error (active) E0140 Too many arguments in function call  D:\scitools\DevSoft\gmp\mpir\x64\Release\mpreal.h 590_

Anyone know how to fix it?

**Comment by advanpix** [comment]
This issue was fixed a long time ago #7. Download MPFR C++ from github.
