### ISSUE TITLE
Preprocessor definition `IsInf` may conflict with other libraries

### ISSUE THREAD

**Issue by vdilecce** [advanpix/mpreal#21]
Defining `IsInf` (lines 77-83) may cause conflicts with other libraries (e.g. VTK's `vtkMath::IsInf()`).

Maybe `MPREAL_ISINF` could be a sensible alternative?

**Comment by advanpix** [comment]
I think it is a good idea. Please make pull request with the changes. Or let me know if you prefer me doing it.

**Comment by vdilecce** [comment]
Sorry for the late response. You can go ahead with the modification. Thank you!

**Comment by advanpix** [comment]
Fixed by https://github.com/advanpix/mpreal/commit/6ad3016f33329ba8f5b6b4bb956e275abe6da411
