### ISSUE TITLE
Definitions of max and min are in conflict with those in <algorithm>

### ISSUE THREAD

**Issue by cffk** [advanpix/mpreal#9]
The definitions of max and min are in conflict with those in `<algorithm>` leading to errors of the form "call of overloaded `max(...)` is ambiguous.  The fix is to make the `omitnan` argument to max and min required.

**Comment by cantonios** [comment]
+1

**Comment by advanpix** [comment]
Fixed with the commit 269a03782fa0b87c20470976b88677266c5423ad

**Comment by cffk** [comment]
Thanks for version 3.6.9!  I'm now compiling mpreal support into GeographicLib without needing to apply any patches to ``mpreal.h``.
